"""rename categories to category

Revision ID: da1300047b45
Revises: 1c282ae063ad
Create Date: 2026-08-15 14:31:07.884794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1300047b45'
down_revision = '1c282ae063ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_category_id_fkey', type_='foreignkey')
    
    # Create new category table
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Drop old categories table
    op.drop_table('categories')
    
    # Recreate the foreign key with the new table name
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('products_category_id_fkey', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('products_category_id_fkey', 'categories', ['category_id'], ['id'])

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.drop_table('category')
    # ### end Alembic commands ###
