import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="flex justify-between items-center border-b px-6 py-3">
      <span className="font-bold text-lg">RevoShop</span>

      <NavBar></NavBar>
    </header>
  );
}

function Footer() {
  return (
    <footer className="border-t px-6 py-3 text-center text-gray-400 text-sm">
      Footer — app/layout.tsx
    </footer>
  );
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
          {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
