FROM postgres:18

ENV POSTGRES_DB=learning_db
ENV POSTGRES_USER=ismail
ENV POSTGRES_PASSWORD=postgres123

EXPOSE 5432

# docker build -t revou-postgres-img .
# docker run -d --name=revou-postgres -p 5433:5432 -v "$(pwd)/data:/var/lib/postgresql/data" revou-postgres-img